services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - TESSERACT_CMD=/usr/bin/tesseract
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
